"""Interfaces used by OCR, checked against the installed pypdfium2 helpers."""

from PIL.Image import Image

class PdfBitmap:
    def to_pil(self) -> Image: ...

class PdfPage:
    def render(self, scale: float = ...) -> PdfBitmap: ...

class PdfDocument:
    def __init__(self, input: bytes) -> None: ...
    def __getitem__(self, index: int) -> PdfPage: ...
    def close(self) -> None: ...
