from apscheduler.job import Job
from apscheduler.schedulers.base import BaseScheduler

class SQLAlchemyJobStore:
    def __init__(self, *, url: str) -> None: ...
    def start(self, scheduler: BaseScheduler, alias: str) -> None: ...
    def get_all_jobs(self) -> list[Job]: ...
