"""Revision f8a9b0c1d2e3 shipped twice: market_price_runs here, AI usage on PR 27.

The owner's laptop database ran PR 27: it is stamped f8a9b0c1d2e3, has the PR 27
usage tables and seeded prices, and has no market_price_runs. ``upgrade head``
must leave it with the same schema as a fresh database, keep stored rows, and
apply the a9b0c1d2e3f4 status change.
"""

from __future__ import annotations

import os
from collections.abc import Iterator
from contextlib import contextmanager
from decimal import Decimal
from uuid import uuid4

import pytest
from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine, make_url

from alembic import command
from govcon.cli import alembic_config

HEAD = "d2e3f4a5b6c7"
BEFORE_CONFLICT = "e7f8a9b0c1d2"
CONFLICT = "f8a9b0c1d2e3"

# PR 27 (commit 442d7a2) revision f8a9b0c1d2e3, frozen as the SQL it created.
PR27_USAGE_DDL = """
CREATE TABLE ai_model_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    provider TEXT NOT NULL,
    model TEXT NOT NULL,
    input_usd_per_million NUMERIC NOT NULL,
    output_usd_per_million NUMERIC NOT NULL,
    cached_usd_per_million NUMERIC,
    cache_write_usd_per_million NUMERIC,
    source_url TEXT NOT NULL,
    effective_as_of DATE NOT NULL,
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_ai_model_prices_provider_model UNIQUE (provider, model),
    CONSTRAINT ck_ai_model_prices_nonnegative CHECK (input_usd_per_million >= 0 AND output_usd_per_million >= 0
        AND (cached_usd_per_million IS NULL OR cached_usd_per_million >= 0)
        AND (cache_write_usd_per_million IS NULL OR cache_write_usd_per_million >= 0))
);
CREATE TABLE ai_provider_calls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    opportunity_id BIGINT,
    purpose TEXT NOT NULL,
    provider TEXT NOT NULL,
    model TEXT,
    status TEXT NOT NULL,
    input_tokens BIGINT,
    output_tokens BIGINT,
    cached_tokens BIGINT,
    cache_write_tokens BIGINT,
    latency_ms INTEGER,
    analysis_id BIGINT,
    decision_run_id BIGINT,
    cost_usd NUMERIC,
    price_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT ck_ai_provider_calls_status CHECK (status IN ('succeeded', 'failed', 'blocked', 'local')),
    CONSTRAINT ck_ai_provider_calls_nonnegative CHECK ((input_tokens IS NULL OR input_tokens >= 0)
        AND (output_tokens IS NULL OR output_tokens >= 0)
        AND (cached_tokens IS NULL OR cached_tokens >= 0)
        AND (cache_write_tokens IS NULL OR cache_write_tokens >= 0)
        AND (cost_usd IS NULL OR cost_usd >= 0)
        AND (latency_ms IS NULL OR latency_ms >= 0)),
    FOREIGN KEY(price_id) REFERENCES ai_model_prices (id)
);
CREATE INDEX ix_ai_provider_calls_created_at ON ai_provider_calls (created_at);
CREATE INDEX ix_ai_provider_calls_opportunity_id ON ai_provider_calls (opportunity_id);
CREATE INDEX ix_ai_provider_calls_provider_model ON ai_provider_calls (provider, model);
"""

_DEEPSEEK = "https://api-docs.deepseek.com/quick_start/pricing"
_ANTHROPIC = "https://platform.claude.com/docs/en/about-claude/pricing"
# PR 27 seed rows: (provider, model, input, output, cached, cache_write, source, effective).
PR27_SEED = [
    ("deepseek", "deepseek-flash", "0.15", "0.6", "0.003", None, _DEEPSEEK, "2026-10-10"),
    ("deepseek", "deepseek-v4-flash", "0.15", "0.6", "0.003", None, _DEEPSEEK, "2026-10-10"),
    ("deepseek", "deepseek-v4-pro", "0.66", "1.98", "0.022", None, _DEEPSEEK, "2026-10-10"),
    ("anthropic", "claude-sonnet-5-5", "2", "10", "0.10", "2.50", _ANTHROPIC, "2026-10-07"),
    ("anthropic", "claude-opus-5-5", "4", "20", "0.20", "5", _ANTHROPIC, "2026-10-07"),
    ("anthropic", "claude-opus-5", "5", "25", "0.50", "6.25", _ANTHROPIC, "2026-10-07"),
    ("anthropic", "claude-fable-5", "10", "50", "1", "12.50", _ANTHROPIC, "2026-10-07"),
    # The owner edited this one on the laptop; the upgrade must keep the edit.
    ("anthropic", "claude-fable-5-1", "11", "55", "0.25", "12.50", _ANTHROPIC, "2026-10-08"),
]


@contextmanager
def _scratch_database() -> Iterator[tuple[str, Engine]]:
    base = make_url(os.environ.get("DATABASE_URL", "postgresql+psycopg://govcon:govcon@localhost:5432/govcon"))
    admin = create_engine(base.set(database="postgres"), isolation_level="AUTOCOMMIT")
    name = "govcon_mig_" + uuid4().hex[:12]
    with admin.connect() as connection:
        connection.execute(text(f"CREATE DATABASE {name} TEMPLATE template0"))
    url = base.set(database=name).render_as_string(hide_password=False)
    previous = os.environ.get("GOVCON_ALEMBIC_URL")
    os.environ["GOVCON_ALEMBIC_URL"] = url
    engine = create_engine(url)
    try:
        yield url, engine
    finally:
        engine.dispose()
        if previous is None:
            os.environ.pop("GOVCON_ALEMBIC_URL", None)
        else:
            os.environ["GOVCON_ALEMBIC_URL"] = previous
        with admin.connect() as connection:
            connection.execute(text(f"DROP DATABASE IF EXISTS {name} WITH (FORCE)"))
        admin.dispose()


def _schema(engine: Engine) -> dict[str, set[tuple]]:
    """Columns, constraints and indexes of every table, order-insensitive."""
    with engine.connect() as conn:
        columns = set(tuple(row) for row in conn.execute(text(
            "SELECT table_name, column_name, data_type, is_nullable, coalesce(column_default, ''), is_identity "
            "FROM information_schema.columns WHERE table_schema = current_schema() AND table_name <> 'alembic_version'"
        )))
        constraints = set(tuple(row) for row in conn.execute(text(
            "SELECT t.relname, c.conname, pg_get_constraintdef(c.oid) FROM pg_constraint c "
            "JOIN pg_class t ON t.oid = c.conrelid JOIN pg_namespace n ON n.oid = t.relnamespace "
            "WHERE n.nspname = current_schema() AND t.relname <> 'alembic_version'"
        )))
        indexes = set(tuple(row) for row in conn.execute(text(
            "SELECT tablename, indexname, indexdef FROM pg_indexes "
            "WHERE schemaname = current_schema() AND tablename <> 'alembic_version'"
        )))
    return {"columns": columns, "constraints": constraints, "indexes": indexes}


def _revision(engine: Engine) -> str:
    with engine.connect() as conn:
        return conn.execute(text("SELECT version_num FROM alembic_version")).scalar_one()


def _build_laptop_database(engine: Engine) -> int:
    """PR 27 state: usage tables and prices, stamped f8a9b0c1d2e3, no market_price_runs."""
    cfg = alembic_config()
    command.upgrade(cfg, BEFORE_CONFLICT)
    with engine.begin() as conn:
        conn.exec_driver_sql(PR27_USAGE_DDL)
        for provider, model, inp, out, cached, write, url, effective in PR27_SEED:
            conn.execute(text(
                "INSERT INTO ai_model_prices (provider, model, input_usd_per_million, output_usd_per_million, "
                "cached_usd_per_million, cache_write_usd_per_million, source_url, effective_as_of, note) "
                "VALUES (:p, :m, :i, :o, :c, :w, :u, :e, 'PR 27 seed')"
            ), {"p": provider, "m": model, "i": inp, "o": out, "c": cached, "w": write, "u": url, "e": effective})
        conn.execute(text(
            "INSERT INTO ai_provider_calls (purpose, provider, model, status, input_tokens, output_tokens, cost_usd) "
            "VALUES ('solicitation_analysis', 'deepseek', 'deepseek-flash', 'succeeded', 50, 20, 0.0000195)"
        ))
        opp_id = conn.execute(text(
            "INSERT INTO opportunities (source, source_id, title, status, opportunity_type, raw, links) "
            "VALUES ('sam', :sid, 'Award notice stored as open', 'open', 'Award Notice', '{}'::jsonb, '{}'::jsonb) "
            "RETURNING id"
        ), {"sid": "laptop-" + uuid4().hex}).scalar_one()
    command.stamp(cfg, CONFLICT)
    with engine.connect() as conn:
        assert conn.execute(text("SELECT to_regclass('market_price_runs')")).scalar() is None
    return int(opp_id)


@pytest.mark.usefixtures("upgraded_engine")
def test_fresh_database_reaches_head_with_every_table() -> None:
    with _scratch_database() as (_url, engine):
        command.upgrade(alembic_config(), "head")
        assert _revision(engine) == HEAD
        with engine.connect() as conn:
            for table in ("market_price_runs", "ai_model_prices", "ai_provider_calls"):
                assert conn.execute(text("SELECT to_regclass(:t)"), {"t": table}).scalar() is not None
            rows = conn.execute(text(
                "SELECT provider, model, web_search_usd_per_thousand FROM ai_model_prices ORDER BY provider, model"
            )).all()
            check = conn.execute(text(
                "SELECT pg_get_constraintdef(oid) FROM pg_constraint WHERE conname = 'ck_tasks_task_type'"
            )).scalar_one()
            has_budget = conn.execute(text(
                "SELECT 1 FROM information_schema.columns "
                "WHERE table_name = 'opportunities' AND column_name = 'ai_max_input_tokens'"
            )).scalar()
        assert len(rows) == 8
        assert {row.model for row in rows if row.web_search_usd_per_thousand == Decimal(10)} == {
            "claude-sonnet-5-5", "claude-opus-5-5", "claude-opus-5", "claude-fable-5", "claude-fable-5-1"}
        assert "market_price_research" in check
        assert "attachment_download" in check
        assert has_budget == 1

        # Down past the conflict and back up again: every step is repeatable.
        command.downgrade(alembic_config(), BEFORE_CONFLICT)
        with engine.connect() as conn:
            assert conn.execute(text("SELECT to_regclass('market_price_runs')")).scalar() is None
            assert conn.execute(text("SELECT to_regclass('ai_provider_calls')")).scalar() is None
        command.upgrade(alembic_config(), "head")
        assert _revision(engine) == HEAD


@pytest.mark.usefixtures("upgraded_engine")
def test_laptop_database_stamped_by_pr27_upgrades_to_the_fresh_schema() -> None:
    with _scratch_database() as (_url, fresh):
        command.upgrade(alembic_config(), "head")
        expected = _schema(fresh)

    with _scratch_database() as (_url, engine):
        opp_id = _build_laptop_database(engine)
        command.upgrade(alembic_config(), "head")
        assert _revision(engine) == HEAD
        actual = _schema(engine)
        for part in ("columns", "constraints", "indexes"):
            assert actual[part] - expected[part] == set(), part
            assert expected[part] - actual[part] == set(), part

        with engine.connect() as conn:
            prices = {row.model: row for row in conn.execute(text("SELECT * FROM ai_model_prices")).all()}
            calls = conn.execute(text("SELECT * FROM ai_provider_calls")).all()
            status = conn.execute(text("SELECT status FROM opportunities WHERE id = :id"), {"id": opp_id}).scalar_one()
            conn.execute(text(
                "INSERT INTO tasks (task_type, status, payload, dedup_key) "
                "VALUES ('market_price_research', 'queued', '{}'::jsonb, 'laptop-check')"
            ))
        # No duplicates; untouched PR 27 rows got the cited search fee; the edited row was kept.
        assert len(prices) == 8
        assert prices["claude-sonnet-5-5"].web_search_usd_per_thousand == Decimal(10)
        assert prices["claude-fable-5-1"].input_usd_per_million == Decimal(11)
        assert prices["claude-fable-5-1"].web_search_usd_per_thousand is None
        assert prices["deepseek-flash"].web_search_usd_per_thousand is None
        # The stored call survives with its tokens; server-tool counts were not reported then.
        assert len(calls) == 1 and calls[0].input_tokens == 50 and calls[0].web_search_requests is None
        # a9b0c1d2e3f4 ran: the award notice is no longer open.
        assert status == "awarded"

        # Stepping back to the conflicting revision and up again lands on the same schema.
        command.downgrade(alembic_config(), CONFLICT)
        command.upgrade(alembic_config(), "head")
        assert _schema(engine) == actual
