"""foundation schema

Revision ID: 97cb081e9a8e
Revises: 
Create Date: 2026-09-26 18:15:04.084869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97cb081e9a8e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_UPDATED_AT_TABLES = (
    "opportunities",
    "awards",
    "vendors",
    "contacts",
    "watchlists",
    "matches",
    "users",
    "user_sessions",
    "notifications",
    "review_assignments",
    "review_comments",
    "review_sessions",
    "pursuits",
    "files",
    "prompt_registry",
    "requirements",
    "proposals",
    "requirement_evidence",
    "clause_library",
    "compliance_findings",
    "proposal_sections",
    "submissions",
    "outcome_feedback",
)


def _install_updated_at_triggers() -> None:
    op.execute(
        """
        CREATE OR REPLACE FUNCTION govcon_set_updated_at()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$
        """
    )
    for table in _UPDATED_AT_TABLES:
        op.execute(
            f"""
            CREATE TRIGGER trg_{table}_set_updated_at
            BEFORE UPDATE ON {table}
            FOR EACH ROW
            EXECUTE FUNCTION govcon_set_updated_at()
            """
        )


def _drop_updated_at_triggers() -> None:
    for table in _UPDATED_AT_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_set_updated_at ON {table}")
    op.execute("DROP FUNCTION IF EXISTS govcon_set_updated_at()")


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('awards',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('source', sa.Text(), server_default=sa.text("'usaspending'"), nullable=False),
    sa.Column('award_id', sa.Text(), nullable=False),
    sa.Column('piid', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('psc_code', sa.Text(), nullable=True),
    sa.Column('naics_code', sa.Text(), nullable=True),
    sa.Column('nsn', sa.Text(), nullable=True),
    sa.Column('recipient_uei', sa.Text(), nullable=True),
    sa.Column('recipient_name', sa.Text(), nullable=True),
    sa.Column('awarding_agency', sa.Text(), nullable=True),
    sa.Column('action_date', sa.Date(), nullable=True),
    sa.Column('total_obligation', sa.Numeric(), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=True),
    sa.Column('unit_price', sa.Numeric(), nullable=True),
    sa.Column('set_aside_code', sa.Text(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'award_id', name='uq_awards_source_award_id')
    )
    op.create_index('ix_awards_action_date', 'awards', ['action_date'], unique=False)
    op.create_index('ix_awards_nsn', 'awards', ['nsn'], unique=False)
    op.create_index('ix_awards_psc_code', 'awards', ['psc_code'], unique=False)
    op.create_index('ix_awards_recipient_uei', 'awards', ['recipient_uei'], unique=False)
    op.create_table('clause_library',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('clause_family', sa.Text(), nullable=True),
    sa.Column('clause_number', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('typical_effects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verification_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('default_risk_level', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_version_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clause_family', 'clause_number', name='uq_clause_library_family_number')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('job', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('fetched', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('inserted', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('updated', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('unchanged', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('solicitation_number', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('opportunity_type', sa.Text(), nullable=True),
    sa.Column('psc_code', sa.Text(), nullable=True),
    sa.Column('naics_code', sa.Text(), nullable=True),
    sa.Column('set_aside_code', sa.Text(), nullable=True),
    sa.Column('agency_path', sa.Text(), nullable=True),
    sa.Column('place_of_performance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nsn', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('estimated_value_min', sa.Numeric(), nullable=True),
    sa.Column('estimated_value_max', sa.Numeric(), nullable=True),
    sa.Column('estimated_value_source', sa.Text(), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('response_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'open'"), nullable=False),
    sa.Column('poc', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_hash', sa.Text(), nullable=True),
    sa.Column('embedding', Vector(384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_opportunities_source_source_id')
    )
    op.create_index('ix_opportunities_naics_code', 'opportunities', ['naics_code'], unique=False)
    op.create_index('ix_opportunities_nsn', 'opportunities', ['nsn'], unique=False)
    op.create_index('ix_opportunities_psc_code', 'opportunities', ['psc_code'], unique=False)
    op.create_index('ix_opportunities_response_deadline', 'opportunities', ['response_deadline'], unique=False)
    op.create_index('ix_opportunities_status', 'opportunities', ['status'], unique=False)
    op.create_index('opportunities_fts', 'opportunities', [sa.literal_column("to_tsvector('english', coalesce(title, '') || ' ' || coalesce(description, ''))")], unique=False, postgresql_using='gin')
    op.create_table('prompt_registry',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('prompt_name', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('task_type', sa.Text(), nullable=False),
    sa.Column('provider_family', sa.Text(), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('prompt_hash', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Text(), nullable=True),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('default_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allowed_data_classes', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_name', 'prompt_version', name='uq_prompt_registry_name_version')
    )
    op.create_index('prompt_registry_one_active', 'prompt_registry', ['prompt_name'], unique=True, postgresql_where=sa.text('active = true'))
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), server_default=sa.text("'reviewer'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'approver', 'reviewer', 'read_only')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_table('vendors',
    sa.Column('uei', sa.Text(), nullable=False),
    sa.Column('cage_code', sa.Text(), nullable=True),
    sa.Column('legal_name', sa.Text(), nullable=True),
    sa.Column('dba_name', sa.Text(), nullable=True),
    sa.Column('registration_status', sa.Text(), nullable=True),
    sa.Column('physical_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('business_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('naics_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('psc_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('points_of_contact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uei')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('psc_codes', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('naics_codes', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('exclude_keywords', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('nsn_list', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('set_asides', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('max_value', sa.Numeric(), nullable=True),
    sa.Column('min_value', sa.Numeric(), nullable=True),
    sa.Column('min_deadline_days', sa.Integer(), nullable=True),
    sa.Column('sources', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_analyses',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('opportunity_id', sa.BigInteger(), nullable=False),
    sa.Column('analysis_type', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('prompt_name', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('prompt_hash', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.Text(), nullable=True),
    sa.Column('generation_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('input_snapshot_hash', sa.Text(), nullable=True),
    sa.Column('context_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_analyses_opportunity_type_created', 'ai_analyses', ['opportunity_id', 'analysis_type', 'created_at'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('opportunity_id', sa.BigInteger(), nullable=True),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_opportunity_created', 'audit_events', ['opportunity_id', 'created_at'], unique=False)
    op.create_index('ix_audit_events_user_created', 'audit_events', ['user_id', 'created_at'], unique=False)
    op.create_table('bid_decisions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('opportunity_id', sa.BigInteger(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('recommendation_score', sa.Numeric(), nullable=True),
    sa.Column('capability_score', sa.Numeric(), nullable=True),
    sa.Column('pricing_score', sa.Numeric(), nullable=True),
    sa.Column('past_performance_score', sa.Numeric(), nullable=True),
    sa.Column('deadline_score', sa.Numeric(), nullable=True),
    sa.Column('competition_score', sa.Numeric(), nullable=True),
    sa.Column('margin_score', sa.Numeric(), nullable=True),
    sa.Column('compliance_risk_score', sa.Numeric(), nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missing_information', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rules_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('jev_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('human_decision', sa.Text(), nullable=True),
    sa.Column('human_comments', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("human_decision IS NULL OR human_decision IN ('approve_bid', 'no_bid', 'defer')", name='ck_bid_decisions_human_decision'),
    sa.CheckConstraint("recommendation IN ('bid', 'no_bid', 'review', 'insufficient_information')", name='ck_bid_decisions_recommendation'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bid_decisions_opportunity_created', 'bid_decisions', ['opportunity_id', 'created_at'], unique=False)
    op.create_table('compliance_runs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('opportunity_id', sa.BigInteger(), nullable=False),
    sa.Column('run_type', sa.Text(), nullable=False),
    sa.Column('run_version', sa.Text(), nullable=False),
    sa.Column('source_snapshot_ids', postgresql.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('input_hash', sa.Text(), nullable=True),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mandatory_total', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('mandatory_satisfied', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('mandatory_missing', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('mandatory_unknown', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('mandatory_needs_review', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('critical_total', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('critical_satisfied', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('critical_unresolved', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('false_satisfied_detected', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('agency_path', sa.Text(), nullable=True),
    sa.Column('contact_type', sa.Text(), nullable=True),
    sa.Column('first_seen_opportunity_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['first_seen_opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'agency_path', name='uq_contacts_email_agency_path')
    )
    op.create_table('decision_runs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('opportunity_id', sa.BigInteger(), nullable=True),
    sa.Column('bundle_name', sa.Text(), nullable=False),
    sa.Column('bundle_version', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), server_default=sa.text("'jev'"), nullable=False),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('decision_spec_name', sa.Text(), nullable=True),
    sa.Column('decision_spec_hash', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.Text(), nullable=True),
    sa.Column('input_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_state_hash', sa.Text(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('cost', sa.Numeric(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('source_snapshot_ids', postgresql.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('supersedes_run_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['supersedes_run_id'], ['decision_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decision_runs_opportunity_bundle_created', 'decision_runs', ['opportunity_id', 'bundle_name', 'created_at'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('opportunity_id', sa.BigInteger(), nullable=False),
    sa.Column('watchlist_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('matched_on', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'new'"), nullable=False),
    sa.Column('alerted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('new', 'seen', 'dismissed', 'reviewing', 'pursuing')", name='ck_matches_status'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'watchlist_id', name='uq_matches_opportunity_watchlist')
    )
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('opportunity_id', sa.BigInteger(), nullable=True),
    sa.Column('notification_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("notification_type IN ('review_assigned', 'reviewer_completed', 'new_reviewer_comment', 'ai_flagged_comment_needs_evidence', 'review_quorum_satisfied', 'second_review_required', 'second_review_requested', 'review_reassigned', 'approval_pending', 'material_amendment_after_review', 'proposal_package_generated', 'submission_ready')", name='ck_notifications_type'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_table('opportunity_snapshots',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('opportunity_id', sa.BigInteger(), nullable=False),
    sa.Column('source_version', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'content_hash', name='uq_opportunity_snapshots_opportunity_hash')
    )
    op.create_index('ix_opportunity_snapshots_opportunity_fetched', 'opportunity_snapshots', ['opportunity_id', 'fetched_at'], unique=False)
    op.create_table('pursuits',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('opportunity_id', sa.BigInteger(), nullable=False),
    sa.Column('stage', sa.Text(), server_default=sa.text("'evaluating'"), nullable=False),
    sa.Column('sourcing_cost', sa.Numeric(), nullable=True),
    sa.Column('quote_price', sa.Numeric(), nullable=True),
    sa.Column('margin_pct', sa.Numeric(), sa.Computed('CASE WHEN sourcing_cost > 0 THEN round((quote_price - sourcing_cost) / sourcing_cost * 100, 1) ELSE NULL END', persisted=True), nullable=True),
    sa.Column('supplier', sa.Text(), nullable=True),
    sa.Column('approved_to_bid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("stage IN ('evaluating', 'bid_approved', 'sourcing', 'drafting', 'review', 'ready_to_submit', 'submitted', 'won', 'lost', 'cancelled', 'no_bid')", name='ck_pursuits_stage'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', name='uq_pursuits_opportunity')
    )
    op.create_table('review_assignments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('opportunity_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('assignment_role', sa.Text(), server_default=sa.text("'reviewer'"), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'assigned'"), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('agree_with_ai_assessment', sa.Boolean(), nullable=True),
    sa.Column('second_review_requested', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('second_review_request_reason', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reopened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('assigned', 'in_progress', 'complete', 'reopened')", name='ck_review_assignments_status'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'user_id', name='uq_review_assignments_opportunity_user')
    )
    op.create_table('review_comments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('opportunity_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_comment_id', sa.BigInteger(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_recommendation', sa.Text(), nullable=True),
    sa.Column('ai_position', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.Text(), nullable=True),
    sa.Column('ai_reason', sa.Text(), nullable=True),
    sa.Column('ai_supporting_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_contradicting_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_missing_information', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_suggested_action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['review_comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_notes',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('opportunity_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('note_type', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('opportunity_id', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('sha256', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extraction_status', sa.Text(), nullable=True),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['opportunity_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'url', 'sha256', name='uq_files_opportunity_url_sha256')
    )
    op.create_table('opportunity_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('opportunity_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('field_name', sa.Text(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['opportunity_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_opportunity_events_opportunity_detected', 'opportunity_events', ['opportunity_id', 'detected_at'], unique=False)
    op.create_table('outcome_feedback',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('opportunity_id', sa.BigInteger(), nullable=False),
    sa.Column('pursuit_id', sa.BigInteger(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('no_bid_reason', sa.Text(), nullable=True),
    sa.Column('loss_reason', sa.Text(), nullable=True),
    sa.Column('win_reason', sa.Text(), nullable=True),
    sa.Column('awarded_vendor_uei', sa.Text(), nullable=True),
    sa.Column('awarded_vendor_name', sa.Text(), nullable=True),
    sa.Column('award_amount', sa.Numeric(), nullable=True),
    sa.Column('award_date', sa.Date(), nullable=True),
    sa.Column('government_feedback', sa.Text(), nullable=True),
    sa.Column('debrief_notes', sa.Text(), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('user_tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['pursuit_id'], ['pursuits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposals',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('opportunity_id', sa.BigInteger(), nullable=False),
    sa.Column('pursuit_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('current_version_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['pursuit_id'], ['pursuits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', name='uq_proposals_opportunity')
    )
    op.create_table('review_sessions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('opportunity_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('ai_decision_package_id', sa.BigInteger(), nullable=True),
    sa.Column('review_policy', sa.Text(), server_default=sa.text("'conditional'"), nullable=False),
    sa.Column('required_review_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('completed_review_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('second_review_required', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('second_review_reason', sa.Text(), nullable=True),
    sa.Column('reviewer_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_consolidated_review', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_approval_status', sa.Text(), nullable=True),
    sa.Column('approved_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('override_used', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('override_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('override_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("review_policy IN ('single', 'dual', 'conditional')", name='ck_review_sessions_policy'),
    sa.CheckConstraint("status IN ('pending', 'ready_for_review', 'under_review', 'review_complete', 'approval_pending', 'approved_to_bid', 'returned_for_review', 'no_bid')", name='ck_review_sessions_status'),
    sa.ForeignKeyConstraint(['ai_decision_package_id'], ['ai_analyses.id'], ),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['override_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', name='uq_review_sessions_opportunity')
    )
    op.create_table('submissions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('opportunity_id', sa.BigInteger(), nullable=False),
    sa.Column('pursuit_id', sa.BigInteger(), nullable=False),
    sa.Column('submission_method', sa.Text(), nullable=True),
    sa.Column('submission_destination', sa.Text(), nullable=True),
    sa.Column('portal_name', sa.Text(), nullable=True),
    sa.Column('portal_url', sa.Text(), nullable=True),
    sa.Column('recipient_email', sa.Text(), nullable=True),
    sa.Column('submission_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_timezone', sa.Text(), nullable=True),
    sa.Column('required_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('readiness_status', sa.Text(), server_default=sa.text("'not_ready'"), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmation_number', sa.Text(), nullable=True),
    sa.Column('confirmation_file', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'preparing'"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("status IN ('preparing', 'ready', 'submitted', 'confirmed', 'failed', 'withdrawn')", name='ck_submissions_status'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['pursuit_id'], ['pursuits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposal_versions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('proposal_id', sa.BigInteger(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id', 'version_number', name='uq_proposal_versions_proposal_number')
    )
    op.create_foreign_key(
        "fk_proposals_current_version_id",
        "proposals",
        "proposal_versions",
        ["current_version_id"],
        ["id"],
    )
    op.create_table('requirements',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('opportunity_id', sa.BigInteger(), nullable=False),
    sa.Column('source_file_id', sa.BigInteger(), nullable=True),
    sa.Column('source_snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('requirement_type', sa.Text(), nullable=True),
    sa.Column('requirement_text', sa.Text(), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('source_section', sa.Text(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('source_text_hash', sa.Text(), nullable=True),
    sa.Column('extraction_pass', sa.Text(), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(), nullable=True),
    sa.Column('independently_confirmed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('response_required', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'unreviewed'"), nullable=False),
    sa.Column('assigned_proposal_section', sa.Text(), nullable=True),
    sa.Column('response_notes', sa.Text(), nullable=True),
    sa.Column('stale_due_to_amendment', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('superseded_by_requirement_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.Text(), server_default=sa.text("'ai'"), nullable=False),
    sa.Column('verified_by_human', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('unreviewed', 'satisfied', 'missing', 'unknown', 'needs_review', 'not_applicable', 'stale', 'superseded')", name='ck_requirements_status'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['opportunity_snapshots.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_requirements_opportunity_status', 'requirements', ['opportunity_id', 'status'], unique=False)
    op.create_table('compliance_findings',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('opportunity_id', sa.BigInteger(), nullable=False),
    sa.Column('requirement_id', sa.BigInteger(), nullable=True),
    sa.Column('finding_type', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'open'"), nullable=False),
    sa.Column('detected_by', sa.Text(), nullable=True),
    sa.Column('detector_version', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposal_sections',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('proposal_version_id', sa.BigInteger(), nullable=False),
    sa.Column('section_key', sa.Text(), nullable=True),
    sa.Column('heading', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('requirement_ids', postgresql.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_version_id'], ['proposal_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirement_evidence',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('requirement_id', sa.BigInteger(), nullable=False),
    sa.Column('evidence_type', sa.Text(), nullable=False),
    sa.Column('source_file_id', sa.BigInteger(), nullable=True),
    sa.Column('proposal_version_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_section', sa.Text(), nullable=True),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('evidence_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verification_method', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.Text(), server_default=sa.text("'unverified'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_version_id'], ['proposal_versions.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    _install_updated_at_triggers()


def downgrade() -> None:
    _drop_updated_at_triggers()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requirement_evidence')
    op.drop_table('proposal_sections')
    op.drop_table('compliance_findings')
    op.drop_index('ix_requirements_opportunity_status', table_name='requirements')
    op.drop_table('requirements')
    op.drop_constraint("fk_proposals_current_version_id", "proposals", type_="foreignkey")
    op.drop_table('proposal_versions')
    op.drop_table('submissions')
    op.drop_table('review_sessions')
    op.drop_table('proposals')
    op.drop_table('outcome_feedback')
    op.drop_index('ix_opportunity_events_opportunity_detected', table_name='opportunity_events')
    op.drop_table('opportunity_events')
    op.drop_table('files')
    op.drop_index('ix_user_sessions_user_id', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('review_notes')
    op.drop_table('review_comments')
    op.drop_table('review_assignments')
    op.drop_table('pursuits')
    op.drop_index('ix_opportunity_snapshots_opportunity_fetched', table_name='opportunity_snapshots')
    op.drop_table('opportunity_snapshots')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('matches')
    op.drop_index('ix_decision_runs_opportunity_bundle_created', table_name='decision_runs')
    op.drop_table('decision_runs')
    op.drop_table('contacts')
    op.drop_table('compliance_runs')
    op.drop_index('ix_bid_decisions_opportunity_created', table_name='bid_decisions')
    op.drop_table('bid_decisions')
    op.drop_index('ix_audit_events_user_created', table_name='audit_events')
    op.drop_index('ix_audit_events_opportunity_created', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_ai_analyses_opportunity_type_created', table_name='ai_analyses')
    op.drop_table('ai_analyses')
    op.drop_table('watchlists')
    op.drop_table('vendors')
    op.drop_table('users')
    op.drop_index('prompt_registry_one_active', table_name='prompt_registry', postgresql_where=sa.text('active = true'))
    op.drop_table('prompt_registry')
    op.drop_index('opportunities_fts', table_name='opportunities', postgresql_using='gin')
    op.drop_index('ix_opportunities_status', table_name='opportunities')
    op.drop_index('ix_opportunities_response_deadline', table_name='opportunities')
    op.drop_index('ix_opportunities_psc_code', table_name='opportunities')
    op.drop_index('ix_opportunities_nsn', table_name='opportunities')
    op.drop_index('ix_opportunities_naics_code', table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_table('ingestion_runs')
    op.drop_table('clause_library')
    op.drop_index('ix_awards_recipient_uei', table_name='awards')
    op.drop_index('ix_awards_psc_code', table_name='awards')
    op.drop_index('ix_awards_nsn', table_name='awards')
    op.drop_index('ix_awards_action_date', table_name='awards')
    op.drop_table('awards')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector")
